### ISSUE TITLE
自动生成的资源索引文件导致编译失败

### ISSUE THREAD

**Issue by lxholding** [Fly-Mix/flr-vscode-extension#10]
首先感谢作者制作分享了此插件 ，感谢：）

自动生成的r.g.dart文件的头部引入如下两个不存在的svga文件，导致编译失败
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

**Comment by CodeEagle** [comment]
你的 pubspac.yaml 有r_library

**Comment by lxholding** [comment]
> 你的 pubspac.yaml 有r_library 的依赖吗？
> 'r_dart_library: 0.4.0-nullsafety.0'

看了一下没有这个依赖，我用的fultter是2.2的已经包含空安全特性

**Comment by CodeEagle** [comment]
要加这个依赖的
详情看
https://github.com/Fly-Mix/flutter_r_demo/blob/master/pubspec.yaml#L10

**Comment by lxholding** [comment]
了解了，谢谢
