### ISSUE TITLE
使用多语言插件后如何获取用户系统当前的countryCode?

### ISSUE THREAD

**Issue by lxholding** [Fly-Mix/flr-vscode-extension#11]
由于在App入口处已经设置了由插件生成的 S.delegate.supportedLocales，里面是不包含countryCode的，此时应该如何获取用户系统的真实countryCode?

**Comment by CodeEagle** [comment]
没看懂什么意思，这个插件的功能更多的是资源文件的管理，没涉及到多语言的管理

**Comment by lxholding** [comment]
是这样的，没有使用插件的情况下使用以下代码可以获取到ios系统的当前的城市码，但是使用插件后supportedLocales已经被替换为 S.delegate.supportedLocales，这个时候再用以下代码获取到的countryCode是空的
`
Locale locale = Localizations.localeOf(context);
locale.countryCode
`

**Comment by CodeEagle** [comment]
上传个 demo 看下吧

**Comment by lxholding** [comment]
谢谢，我找到别的方式来获取了，刚上手flutter还不是很熟悉，打扰了
