### ISSUE TITLE
Removes uses-material-design: true from pubspec.yaml

### ISSUE THREAD

**Issue by Prn-Ice** [Fly-Mix/flr-vscode-extension#4]
![Peek 2020-06-12 15-27](https://user-images.githubusercontent.com/48252841/84513496-6ae0bb80-acc1-11ea-85fc-82229a246598.gif)

**Comment by YK-Unit** [comment]
@Prn-Ice  It'll be fixed at next version, which is a bug in generating flutter-config. Sorry for your inconvenience.

**Comment by YK-Unit** [comment]
It's fixed at v2.1.3 now. Please upgrade flr-vscode-extension to version 2.1.3.
