### ISSUE TITLE
Support null safety.

### ISSUE THREAD

**Issue by Prn-Ice** [Fly-Mix/flr-vscode-extension#8]
Just migrated to null safety and the r.g.dart is filled with null safety errors.

**Comment by YK-Unit** [comment]
- [flr-cli-v3.2.0](flr-cli-v3.2.0)  which supports for nullsafety is released , and you can install it now. See more details from https://github.com/Fly-Mix/flr-cli .
- flr-vscode-extension is still developing for nullsafety--and in fact it needs some time.
